config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  get '/home/turbo_frame_test' => 'home#turbo_frame_test', as: 'turbo_frame_test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @welcome_message = 'Hello, i\'m a dynamic text.'
  end

  def turbo_frame_test; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<article>
  <turbo-frame id="welcome_message">
    <h2> <%= @welcome_message %> </h2>
    <div class="click-me">
      <%= link_to 'Click to change the text', turbo_frame_test_path %>
    </div>
  </turbo-frame>
</article>

app/views/home/turbo_frame_test.html.erb
<turbo-frame id="welcome_message">
  <h2> I'm a new text! </h2>
</turbo-frame>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav data-turbo="false">
  <section>
    <% if user_signed_in? %>
      <span> 
        <%= button_to t('sign_out_button'),
           destroy_user_session_path,
           method: :delete %>
      </span>
    <% else %>
      <span>
        <%= link_to t('sign_in_button'), new_user_session_path %> 
      </span>
      <span> 
        <%= link_to t('sign_up_button'), new_user_registration_path %> 
      </span>
    <% end %>
  <ul>
</nav>